using Microsoft.Extensions.AI;
using System.Collections.Generic;

namespace Chat2Report.Models
{
    /// <summary>
    /// Represents the content required to render a chart in the UI.
    /// </summary>
    public class ChartContent : AIContent
    {
        /// <summary>
        /// The type of chart (e.g., "gantt", "pie", "bar").
        /// </summary>
        public string ChartType { get; set; } = string.Empty;

        /// <summary>
        /// The name of the JavaScript library used to render the chart (e.g., "Mermaid", "ChartJs").
        /// </summary>
        public string Library { get; set; } = string.Empty;

        /// <summary>
        /// The configuration options for the chart, typically generated by an LLM.
        /// For Mermaid, this will be the full Mermaid diagram syntax.
        /// For Chart.js, this will be a JSON string with configuration.
        /// </summary>
        public string Options { get; set; } = string.Empty;


        /// <summary>
        /// 
        /// The name of the JavaScript function to call for rendering this chart.
        /// This is dynamically determined based on the chart library and type.
        /// </summary>
        public string JsRenderFunction { get; set; }

        /// <summary>
        /// The actual data rows to be displayed in the chart.
        /// This is used by renderers like Chart.js that separate configuration from data.
        /// </summary>
        public IReadOnlyList<IReadOnlyDictionary<string, object?>>? Rows { get; set; }


        /// <summary>
        /// Initializes a new instance of the <see cref="ChartContent"/> class.
        /// This constructor is needed for object initializers and serialization.
        /// </summary>
        public ChartContent()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChartContent"/> class.
        /// </summary>
        /// <param name="options">The chart configuration options.</param>
        /// <param name="rows">The data rows for the chart.</param>
        public ChartContent(string options, IReadOnlyList<IReadOnlyDictionary<string, object?>>? rows = null)
        {
            Options = options;
            Rows = rows;
        }
    }
}

